include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - prefer_single_quotes
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - always_put_control_body_on_new_line
    - avoid_empty_else
    - empty_statements
    - unawaited_futures
    - avoid_relative_lib_imports
    - require_trailing_commas

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
